### ISSUE TITLE
FetchService not available in Libp2p

### ISSUE THREAD

**Issue by on-meetsys** [libp2p/js-libp2p#1514]
- **Version**: 0.40
#### Description:
In the [fetch example ](https://github.com/libp2p/js-libp2p/blob/199395de4d8139cc77d0b408626f37c9b8520d28/src/fetch/README.md) it is said to do : 
```
import { createLibp2p } from 'libp2p'
const libp2p = Libp2p.create(...)
```
It looks like this code is not consistent (`createLibp2p` or `Libp2p.create`?). If I use the `createLibp2p` function, it returns a [Libp2p](https://github.com/libp2p/js-libp2p/blob/99446ff0e85e47cae5524c5588fb9a08028c7c70/src/index.ts#L132), which does not have the FetchService available.
And the Libp2p.create() is not available : 
```
import type { Libp2p } from 'libp2p';
const libp2p = Libp2p.create(...)
```
returns an error.
I think this example should be better explained, and I wonder why FetchService is not available in Libp2p

I moreover have noticed a few definitions incompatibilities, for example : 
```
const { createLibp2pNode } = await import('libp2p/src/libp2p'); // V0.40.0
const { gossipsub } = await import('@chainsafe/libp2p-gossipsub'); // V5.2.1
const libp2pnode = await createLibp2pNode({
  pubsub: gossipsub(),
}
```
it works... but with an error telling  `GossipSubComponents` and `Components` are not compatible, due to `acceptIncomingConnection` and `afterUpgradeInbound` not defined in the `ConnectionManager` 
(I add this because I wonder if the libp2p V0.40.0 may have modified some declarations with border effets).

**Comment by achingbrain** [comment]
The docs are out of date, this should be fixed by https://github.com/libp2p/js-libp2p/pull/1516

The way to create your node is:

```js
import { createLibp2p } from 'libp2p'

const node = await createLibp2p()
```

You can use the fetch protocol with:

```js
const result = await node.fetch(peerId, 'some-key')
```

Please see the [fetch test suite](https://github.com/libp2p/js-libp2p/blob/master/test/fetch/fetch.node.ts) for further runnable examples.

**Comment by on-meetsys** [comment]
Thanks. I thought so, but `createLibp2p()` returns a [Libp2p](https://github.com/libp2p/js-libp2p/blob/99446ff0e85e47cae5524c5588fb9a08028c7c70/src/index.ts#L132) object, which does not have any `fetchService` needed to `fetchService.registerLookupFunction()`.

The 'fetch test suite'  uses `createLibp2pNode()`, which returns a `Libp2pNode` which has a `fetchService` member.

The [code](https://github.com/libp2p/js-libp2p/blob/61fcc0b688214d3f8c84bc68bd6192738ae0fdfd/src/index.ts#L219) of `CreateLibp2p` shows it casts the` Libp2pNode` to a` Libp2p`.
I've thought to call `CreateLibp2pNode()` but it is not exported...

So, this is still confusing : why `Libp2p` does not have any `fetchService`, end/or why `CreateLibp2p` calls `CreateLibp2pNode` but returns a `Libp2p` ? I think there is something not clear here.

**Comment by achingbrain** [comment]
Oh that's a good point, I think it's just missing from the types.

**Comment by on-meetsys** [comment]
Something may be missing indeed :) I imagine `fetchService` will be added in `Libp2p`? 
For now, I can patch `Libp2p` but a fix is welcome. Thanks.

**Comment by mpetrunic** [comment]
This is fixed in https://github.com/libp2p/js-libp2p/pull/1476 where Libp2p type is used from @libp2p/interface-libp2p which contains FetchService. You can try it out with installing ` libp2p@next`

**Comment by on-meetsys** [comment]
Fine. I indeed now have access to `fetchService`.

Coming from libp2p@0.40.1 I have side effects upgrading to `"libp2p": "^0.42.1-9a6022b7"`, even after a full refresh of all libraries (yarn).

- a conflict in PeerId, in this kind of code : 
```
import { PeerId } from '@libp2p/interface-peer-id';

const { createFromPubKey } = await import('@libp2p/peer-id-factory');
const { unmarshalPublicKey } = await import('@libp2p/crypto/keys');
const uint8ArrayFromString = (await import('uint8arrays/from-string')).fromString;

const publicKey = unmarshalPublicKey(uint8ArrayFromString(publickey, 'base64pad'));
const peer: PeerId = await createFromPubKey(publicKey); // <- import conflict here
```
which does not appear anymore by importing : 
```
import { PeerId } from '@libp2p/peer-id-factory/node_modules/@libp2p/interface-peer-id';
```

- same kind of PeerId conflict in mdns : 
```
const { createLibp2p } = await import('libp2p');
const { mdns } = await import('@libp2p/mdns');
libp2pnode = await createLibp2p({
      ...,
      peerDiscovery: [
          mdns(), // <- this raises a error about a PeerId import conflict in libs
    ],
})
```

- It is said [here](https://github.com/libp2p/js-libp2p/blob/master/doc/migrations/v0.41-v0.42.md) to subscribe to events with '.on' : 
```

libp2pnode.on('peer:connect', async (evt) => {});
```
but `.on` seems not be defined.

I know it not related to this issue, sorry if it is not the place to post this.

**Comment by achingbrain** [comment]
> a conflict in PeerId, in this kind of code

Please upgrade all of your `@libp2p/*` dependencies, you probably have old versions hanging around.

> but `.on` seems not be defined.

Ah, good catch - it should be `addEventListenter` from the [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) API - I've updated the docs.

**Comment by on-meetsys** [comment]
I have removed all `node_modules` though and made a `yarn`, and the error still persist.
Could there be another lib in my `packages.js` importing libp2p which creates this conflict ?
````
    "@chainsafe/libp2p-gossipsub": "^5.4.1",
    "@libp2p/webrtc-star-signalling-server": "^2.0.5",
    "ipfs": "^0.65.0",
    "ipfs-only-hash": "^4.0.0",
    "libp2p": "^0.42.1-9a6022b7",
    "libp2p-crypto": "^0.21.2",
````
If needed, I can try to make a small project with shows the conflict to go further.

(and I have made an issue with it because my comment was not related to this issue. Sorry to bother twice... We can discuss here or in the new issue, I don't know what is the better)
